skills_set = [[48, 'Advertising'],
[31, 'Applications'],
[1, 'Artifical Intelligence'],
[77, 'Auditing'],
[10, 'Business'],
[73, 'Business Development'],
[30, 'Business Services'],
[78, 'Business Strategy'],
[96, 'Change management'],
[39, 'Cloud Computing'],
[92, 'Commercial Real Estate'],
[13, 'Communication'],
[87, 'Compliance'],
[28, 'Computer Program'],
[80, 'Construction'],
[63, 'Corporate Law'],
[15, 'Customer Service'],
[4, 'Data Analytics'],
[56, 'Data Engineering'],
[12, 'Database Design'],
[82, 'Editing'],
[100, 'Facilities Management'],
[5, 'Financial Accounting'],
[32, 'Financial Reporting'],
[7, 'Goal-Driven'],
[3, 'Graphic Design'],
[97, 'Heavy Equipment'],
[66, 'Human resources'],
[94, 'Information Technology'],
[89, 'Innovation'],
[69, 'Internal Audit'],
[88, 'Legal'],
[2, 'Machine Learning'],
[9, 'Management'],
[93, 'Management Consulting'],
[53, 'Managerial Accounting'],
[68, 'Manufacturing'],
[6, 'Marketing'],
[59, 'Marketing Strategy'],
[60, 'Materials Engineering'],
[91, 'Mentoring'],
[17, 'Microsoft Excel'],
[14, 'Microsoft Office'],
[33, 'Microsoft Word'],
[101, 'Mobile Application Development'],
[36, 'Negotiation'],
[38, 'Networking Automation'],
[65, 'New business development'],
[62, 'Order Fulfillment'],
[24, 'Organization'],
[57, 'Performance Tuning'],
[64, 'Photoshop'],
[90, 'Policy'],
[35, 'Powerpoint'],
[79, 'Presentations'],
[58, 'Problem Solving'],
[95, 'Process Improvement'],
[76, 'Product Development'],
[34, 'Program Management'],
[18, 'Project Management'],
[27, 'Project Planning'],
[75, 'Public Relations'],
[67, 'Public speaking'],
[45, 'QA Testing'],
[81, 'Real Estate'],
[61, 'Recruiting'],
[11, 'Sales'],
[83, 'Sales Management'],
[54, 'Social Media Marketing'],
[37, 'Software Development'],
[29, 'Strategic Planning'],
[70, 'strategy'],
[55, 'Teaching'],
[84, 'Team Building'],
[8, 'Teamwork'],
[26, 'Time Management'],
[74, 'Windows']
]